baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Akr1monia'
theme = 'not-much' 

[markup]
  [markup.highlight]
    style = 'dracula'
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[params]
theme = "dark"
palette = "dracula"
showThemeNotice = true
showPostsSummary = true

# Navigation
[menu]
  [[menu.main]]
    identifier = "home"
    name = "home"
    title = "Home"
    url = "/"
    weight = 1
  
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/posts"
    weight = 2


[caches]
  [caches.images]
    dir = ':cacheDir/images'